name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EVE_CLIENT_ID: ${{ secrets.EVE_CLIENT_ID }}
      EVE_CLIENT_SECRET: ${{ secrets.EVE_CLIENT_SECRET }}
      EVE_CALLBACK_URL: ${{ secrets.EVE_CALLBACK_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Create .env file
        run: |
          mkdir -p internal/embed/config
          echo "EVE_CLIENT_ID=${EVE_CLIENT_ID}" >> internal/embed/config/.env
          echo "EVE_CLIENT_SECRET=${EVE_CLIENT_SECRET}" >> internal/embed/config/.env
          echo "EVE_CALLBACK_URL=${EVE_CALLBACK_URL}" >> internal/embed/config/.env
          echo "SECRET_KEY=${SECRET_KEY}" >> internal/embed/config/.env

      - name: Install Dependencies
        run: |
          npm install
          cd renderer
          npm install

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Install dependencies
        run: npm install

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386 
          sudo apt-get update
          sudo apt-get install -y wine32

      - name: Clean up old build directories
        run: |
          rm -rf dist release
          mkdir dist release

      - name: Create .env file
        run: |
          mkdir -p internal/embed/config
          echo "EVE_CLIENT_ID=${{ secrets.EVE_CLIENT_ID }}" >> internal/embed/config/.env
          echo "EVE_CLIENT_SECRET=${{ secrets.EVE_CLIENT_SECRET }}" >> internal/embed/config/.env
          echo "EVE_CALLBACK_URL=${{ secrets.EVE_CALLBACK_URL }}" >> internal/embed/config/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> internal/embed/config/.env

      - name: Build Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package:app

      # Automatically bump/tag on each push to main
      - name: Bump Tag
        id: increment_tag
        uses: anothrNick/github-tag-action@1.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This ensures the action only bumps the tag for pushes on the main branch
          release_branches: main
          # Options: major, minor, patch (default). Adjust to your preference.
          default_bump: patch
          tag_prefix: 'v'

      - name: Generate Changelog
        id: changelog
        run: |
          # We'll try to retrieve the previous tag. If none exists, we'll do an initial changelog.
          if git describe --tags --abbrev=0 HEAD^ >/dev/null 2>&1; then
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)
            CHANGELOG=$(git log $PREVIOUS_TAG..HEAD --oneline --pretty=format:"- %s")
          else
            echo "No previous tag found, generating initial changelog."
            PREVIOUS_TAG="None"
            CHANGELOG=$(git log --oneline --pretty=format:"- %s")
          fi

          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_ENV
          echo "changelog=$CHANGELOG" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_tag.outputs.new_tag }}
          release_name: Release ${{ steps.increment_tag.outputs.new_tag }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false

      - name: List release directory files
        run: ls -l release

      - name: Set Clean Version
        run: echo "CLEAN_TAG=${{ steps.increment_tag.outputs.new_tag#v }}" >> $GITHUB_ENV

      - name: Upload Release Assets (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "release/CanIFly-Setup-${{ env.CLEAN_TAG }}.exe"
          asset_name: "CanIFly-Setup${{ env.CLEAN_TAG }}.exe"
          asset_content_type: application/x-msdownload
