name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EVE_CLIENT_ID: ${{ secrets.EVE_CLIENT_ID }}
      EVE_CLIENT_SECRET: ${{ secrets.EVE_CLIENT_SECRET }}
      EVE_CALLBACK_URL: ${{ secrets.EVE_CALLBACK_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Create .env file
        run: |
          mkdir -p internal/embed/config
          echo "EVE_CLIENT_ID=${EVE_CLIENT_ID}" >> internal/embed/config/.env
          echo "EVE_CLIENT_SECRET=${EVE_CLIENT_SECRET}" >> internal/embed/config/.env
          echo "EVE_CALLBACK_URL=${EVE_CALLBACK_URL}" >> internal/embed/config/.env
          echo "SECRET_KEY=${SECRET_KEY}" >> internal/embed/config/.env

      - name: Install Dependencies
        run: npm install && cd renderer && npm install

      - name: Run Tests
        run: npm test
